### ISSUE TITLE
Run on CPU

### ISSUE THREAD

**Issue by dezmoanded** [facebookresearch/deepmask#10]
My macbook doesn't have an nvidia gpu. Is there a way to run the pretrained models on the cpu, without CUDA?

**Comment by poliveirap** [comment]
Hi, currently it is only available for CUDA version.
It should not be too difficult to transform the model to work on CPU (just change all the cudnn/cunn.* modules to nn.*), but it would be frustratingly slow

**Comment by poliveirap** [comment]
I'll close thus issue. You can re-open it if you need anything else.

**Comment by maximus009** [comment]
I am running deepmask on a Macbook with CPU-only. I edited the lua files to remove dependancies on cudnn/cunn as suggested.
On running
<br> 
<code> th computeProposals.lua pretrained/deepmask/ </code>
<br>
I am getting the following error.
<code>
"...code/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>"
</code>

Do I need to do anything further in order to get this running without a GPU?

Thanks.

**Comment by poliveirap** [comment]
Yes. The pretrained models have cudnn/cunn everywhere, so you will need to transform all the cunn/cudnn layers into CPU layers (though keeping the same trained weights/biases).
Unfortunately, you will need a cuda compatible version of torch to be able to change it...

**Comment by maximus009** [comment]
Thank you for the response.
Are the CPU compatible models publicly available too? If not, will they be available shortly?
