### ISSUE TITLE
Refine existing mask with SharpMask?

### ISSUE THREAD

**Issue by SergeMv** [facebookresearch/deepmask#3]
Is there a way to refine an existing mask got from elsewhere (say, I have an RGB image file and another 1-channel image file - a mask for the first image) with SharpMask?
If yes, would you give an example code snippet to achieve this?

**Comment by poliveirap** [comment]
It's not possible, since sharpmask requires both the output and the internal feature maps of the forward pass (common trunk). So, it requires a forward pass to have an estimate of the mask ('mask encoding') in order to refine it.
You should maybe try something like the fully connected CRF or some sort of graph cuts.

**Comment by SergeMv** [comment]
Thanks!
