### ISSUE TITLE
poor performance on large size image

### ISSUE THREAD

**Issue by leedewdew** [facebookresearch/deepmask#54]
Dear,

When I try to generate proposals with deepmask on large size image, such as 1280x1280, deepmask shows very poor performance. In fact, I can hardly find proposal whose Iou>0.5.

So, my question is that are there some requirements about the size of input image. I didn't find related information from the paper and internet. So I come up with this question here.

Looking forward to your reply.

**Comment by poliveirap** [comment]
Hi, 
If an image is quite big, the objects present on it might be as well. 
So, in order to the network be able to find these proposals, you might need to change the scales in which it is run (precisely, try to reduce the -si parameter from -2.5 to -3.5 or -3). 
Otherwise, try just to down sample the test image (by half size in each dimension, for example) to see if helps

**Comment by leedewdew** [comment]
Dear Poliveirap,
I have tried the second advice. I works.
Thanks for your nice reply.
